
#!/bin/bash

export OST_UTILITY_GAS_PRICE='0x12A05F200'
export OST_UTILITY_GETH_RPC_PROVIDER='http://127.0.0.1:9546'
export OST_UTILITY_DEPLOYER_ADDR=''
export OST_UTILITY_DEPLOYER_PASSPHRASE='testtest'
export OST_UTILITY_OPS_ADDR=''
export OST_UTILITY_OPS_PASSPHRASE='testtest'
export OST_UTILITY_CHAIN_ID=2000
export OST_AIRDROP_BUDGET_HOLDER=''
export OST_AIRDROP_BUDGET_HOLDER_PASSPHRASE='testtest'

export OP_MYSQL_HOST='127.0.0.1'
export OP_MYSQL_USER='openstuser'
export OP_MYSQL_PASSWORD='ost123'
export OP_MYSQL_DATABASE='payment_development'
export OP_MYSQL_CONNECTION_POOL_SIZE='5'
