
#!/bin/bash

export OST_PRICER_GAS_PRICE='0x12A05F200'
export OST_PRICER_GETH_RPC_PROVIDER='http://127.0.0.1:9546'
export OST_PRICER_GETH_WS_PROVIDER='ws://127.0.0.1:19546'
export OST_PRICER_DEPLOYER_ADDR=''
export OST_PRICER_DEPLOYER_PASSPHRASE='testtest'
export OST_PRICER_OPS_ADDR=''
export OST_PRICER_OPS_PASSPHRASE='testtest'
export OST_PRICER_CONTRACT_ADDR=''
export OST_PRICER_ST_PRIME_UUID=''
export OST_PRICER_CHAIN_ID=2000
